// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char SSID[]     = SECRET_SSID;    // Network SSID (name)
const char PASS[]     = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)

void onGasConcentrationMQ135Change();
void onGasConcentrationMQ2Change();

int gasConcentrationMQ135;
int gasConcentrationMQ2;

void initProperties(){

  ArduinoCloud.addProperty(gasConcentrationMQ135, READWRITE, ON_CHANGE, onGasConcentrationMQ135Change);
  ArduinoCloud.addProperty(gasConcentrationMQ2, READWRITE, 2 * SECONDS, onGasConcentrationMQ2Change);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
